#
# Copyright 2011-2019 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx#license-bsd-2-clause
#

BGFX_DIR=../libs/bgfx
RUNTIME_DIR=../build/assets
BUILD_DIR=../build

include $(BGFX_DIR)/scripts/shader.mk
